<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>SpellFire.RuntimeHost.Cli</RootNamespace>
    <AssemblyName>SpellFire.RuntimeHost.Cli</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpellFire.RuntimeHost\SpellFire.RuntimeHost.csproj" />
  </ItemGroup>

  <Target Name="CopySpellFireHookPayload" AfterTargets="Build">
    <ItemGroup>
      <SpellFireHookPayload Include="..\SpellFire.Hook\bin\$(Configuration)\SpellFire.Hook.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(SpellFireHookPayload)"
          DestinationFiles="@(SpellFireHookPayload->'$(OutputPath)SpellFire.Hook.source.dll')"
          SkipUnchangedFiles="true"
          Condition="Exists('%(SpellFireHookPayload.FullPath)')" />
  </Target>
</Project>
