<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>SpellFire.RobotManager</RootNamespace>
    <AssemblyName>SpellFire.RobotManager</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpellFire.WowRuntime\SpellFire.WowRuntime.csproj" />
  </ItemGroup>
</Project>
